// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgADWAu7qMygauXFbaLTeLhDkojMoRsV8',
    appId: '1:4577595126:web:0cbc68dfb1a2519aa4e6d7',
    messagingSenderId: '4577595126',
    projectId: 'perpustakaan-a89e1',
    authDomain: 'perpustakaan-a89e1.firebaseapp.com',
    storageBucket: 'perpustakaan-a89e1.firebasestorage.app',
    measurementId: 'G-6CTRGSHSL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_c8MT579b_rl_lYZEEcIaPQRwmSUT448',
    appId: '1:4577595126:android:714c057f8b1c38f8a4e6d7',
    messagingSenderId: '4577595126',
    projectId: 'perpustakaan-a89e1',
    storageBucket: 'perpustakaan-a89e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgADWAu7qMygauXFbaLTeLhDkojMoRsV8',
    appId: '1:4577595126:web:533bb438f71ee703a4e6d7',
    messagingSenderId: '4577595126',
    projectId: 'perpustakaan-a89e1',
    authDomain: 'perpustakaan-a89e1.firebaseapp.com',
    storageBucket: 'perpustakaan-a89e1.firebasestorage.app',
    measurementId: 'G-YF8874B5LZ',
  );
}
